# Site settings
name: Adarsh Pandey
title: Adarsh Pandey | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://learneradarsh.github.io/
baseurl: ''
email: learner.adarsh@gmail.com
cover: https://learneradarsh.github.io/img/og.png
logo: https://learneradarsh.github.io/img/emojis/technologist.png
resume: https://learneradarsh.github.io/resume.pdf
linkedin: https://linkedin.com/in/learneradarsh
social:
  - title: email
    url: mailto:learner.adarsh@gmail.com
  - title: leetcode
    url: https://leetcode.com/learneradarsh
  - title: hackerrank
    url: https://hackerrank.com/learner_adarsh
  - title: github
    url: https://github.com/learneradarsh
  - title: linkedin
    url: https://www.linkedin.com/in/learneradarsh

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
